#!/bin/bash

which xmlstarlet >/dev/null || {
 echo "Please install XMLstarlet first."
 exit 2
 }

which mogrify >/dev/null || {
 echo "Please install ImageMagick first."
 exit 2
 }

if [ "$1" = "" ]; then
 exit 1
 fi
rm -fr "Building Instructions [$1]-images"

HTMLFILE="../html/Building Instructions [$1].html"
XHTML="-N xhtml=http://www.w3.org/1999/xhtml"
cat "$HTMLFILE" |\
 tidy -q -numeric -asxhtml --show-warnings no |\
 xmlstarlet ed $XHTML -d "//xhtml:title" |\
 xmlstarlet ed $XHTML -d "//xhtml:div[@class=\"footer\"]" |\
 xmlstarlet ed $XHTML -d "//xhtml:div[@class=\"header\"]" |\
 xmlstarlet ed $XHTML -d "//xhtml:div[@class=\"headerPrint\"]" |\
 xmlstarlet ed $XHTML -d "//xhtml:div[@class=\"nav\"]" |\
 xmlstarlet ed $XHTML -d "//xhtml:div[@class=\"stepdisplay\"]" |\
 xmlstarlet ed $XHTML -d "//xhtml:div[@id=\"step_elements\"]" |\
 xmlstarlet ed $XHTML -d "//xhtml:div[@id=\"step_0\"]" |\
 xmlstarlet ed $XHTML -d "//xhtml:script" |\
 grep -v "display:none;" |\
 grep -v "page-break-after:always;" |\
 sed 's/onload="biStep(0)"//' |\
 sed '/<img /i <br>' |\
 sed 's/height="600" width="800"/height="60%" width="60%"/' |\
 sed 's/height:620px//' |\
 sed '/<div class="step" id="step_1">/i <h1>'$1'</h1>' \
> "$1.html"

cp -a "../html/Building Instructions [$1]-images" "Building Instructions [$1]-images"
rm -fr "Building Instructions [$1]-images/Images"

cd "Building Instructions [$1]-images"

for i in Step*.png; do mogrify -trim -fill white -background white -splice 10x20 -colorize 15% $i; done
for i in Brick*.png; do mogrify -fill white -colorize 20% $i; done

# xmlstarlet ed $XHTML -d "//xhtml:style[@media=\"print\"]" |\
